### PR TITLE
Logout users before login

### PR DESCRIPTION
**Pull request by alexeykazakov**
Related to https://github.com/fabric8-services/fabric8-auth/issues/64

### CODE REVIEW

**Comment by alexeykazakov** [comment]
@dlabrecq could you please review this PR? And I would also need help with babric8-ui to fix it there too.

**Comment by alexeykazakov** [comment]
@dgutride yes, session should be stored in browser. There are both our Keycloak session (sso.openshift.io) + RHD session (developers.redhat.com) which have to be cleared. Don't know details though yet. Have to do some research.

**Comment by dgutride** [comment]
@alexeykazakov  - openid-connect supports requiring the user reauthenticate if a login flow is initiated - can we try that instead?  it seems to be the correct way of solving this:  http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest (see prompt section)

**Comment by dgutride** [comment]
@alexeykazakov  - one more note, it seems this must be done in the keycloak configuration: http://www.keycloak.org/docs/2.3/server_admin_guide/topics/identity-broker/oidc.html by setting the prompt dropdown (I could be way off but that is where my research ended)

**Comment by alexeykazakov** [comment]
@dgutride there are two Keycloaks in our login flow. OSIO Keycloak and RHD. OSIO Keycloak respects prompt=login param and it indeed forces OSIO Keycloak to redirect to RHD Keycloak every time user is trying to login. But RHD Keycloak just ignores this param (I see this param is added to the RHD auth request if I set promt=login in our KC configuration for RHD IdP) and never asks credentials if user is already logged-in to RHD. Maybe it's because the KC version used by RHD has some issue with that param which was fixed later. AFAIK RHD runs some very old Keycloak version (cc: @velias)

Another issue with the promt=login approach is that if we use it we will lose impersonation feature. I checked it. Our KC is always redirects to RHD in this case so we can impersonate in OSIO.

**Comment by alexeykazakov** [comment]
We discussed this issue with the Keycloak team. And it looks like forcing logout is the only option here.

**Comment by dgutride** [comment]
We should definitely see if we can get the red had developers login to schedule an update so we can remove this.

**Comment by joshuawilson** [comment]
@dgutride can you write up an issue to fix/clean this so we don't lose it.

**Comment by alexeykazakov** [comment]
@dgutride Even if RHD upgrades and we can start using the prompt param it will kill our impersonation feature.
What about the login button/link in fabric8-ui? I'm not sure if we should logout force there too right now. Maybe it's worth monitoring how all this works. Users will at least have an option to go to the leading page at openshift.io to login if there is some issue with login from our fabric8-ui app.
WDYT?

**Comment by dgutride** [comment]
I think that makes sense @alexeykazakov  - this is in now so let's see if people can work with it

**Pull request merged**
