### PR TITLE
feat(docs): Add Documentation page with links

### PR DESCRIPTION
**Pull request by mindreeper2420**
Add a Documentation page with link to OpenShift.io Getting Started and User Guides.

screen shot 2018-02-15 at 2 08 07 pm

### CODE REVIEW

**Comment by catrobson** [comment]
@mindreeper2420 can we use the same amount of space as there is between Features and Get Involved before the Documentation 'tab'?

**Comment by mindreeper2420** [comment]
@catrobson good catch - all fixed.

screen shot 2018-02-15 at 2 15 35 pm

**Comment by mindreeper2420** [comment]
screen shot 2018-02-15 at 2 16 06 pm

**Comment by mindreeper2420** [comment]
this PR is related to https://github.com/openshiftio/openshift.io/issues/2215

**Pull request merged**
