### PR TITLE
fix(doc): remove stale PDF documentation in favor of https://docs.ope…

### PR DESCRIPTION
**Pull request by corinnekrych**
…nshift.io/ link
fixes: https://github.com/openshiftio/openshift.io/issues/4162

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by alexeykazakov** [comment]
This PR looks good to me but I'm concerned about old links to https://openshift.io/osiogettingstarted.pdf
Idealy we should redirect all requests from https://openshift.io/osiogettingstarted.pdf to https://docs.openshift.io
Not sure if it's that critical though..

**Comment by corinnekrych** [comment]
@alexeykazakov Let's address the redirect in another PR: https://github.com/openshiftio/openshift.io/pull/4367 (to be tested separately)
this one will focus on correct exiting link.
ok to merge this one?

**Comment by corinnekrych** [comment]
[test]

**Comment by corinnekrych** [comment]
it seems something happened on CI/CD, Friday build was ok, but today build gives:
```
[0mThe command '/bin/sh -c set -ex   && for key in     9554F04D7259F04124DE6B476D5A82AC7E37093B     94AE36675C464D64BAFA68DD7434390BDBE9B9C5     0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93     FD3A5288F042B6850C66B31F09FE44734EB7990E     71DCFD284A79C3B38668286BC97EC7A07EDE3FC1     DD8F2338BAE7501E3DD5AC78C273792F7D83545D     B9AE9905FFD7803F25714661B63B535A4C206CA9     C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8   ; do     gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ||     gpg --keyserver pgp.mit.edu --recv-keys "$key" ||     gpg --keyserver keyserver.pgp.com --recv-keys "$key" ;   done' returned a non-zero code: 2
Connection to 172.19.2.75 closed.
```

**Comment by corinnekrych** [comment]
All green again, I fix CI in separate PR https://github.com/openshiftio/openshift.io/pull/4377 and rebase this PR.

@alexeykazakov @joshuawilson ok to merge this clean-up PR?
for redirect there is another PR we can test on prod-preview.
Once we're happy we can merge both to prod.

**Pull request merged**
