### PR TITLE
fix(doc): add getting started doc

### PR DESCRIPTION
**Pull request by mindreeper2420**

### CODE REVIEW

**Comment by mindreeper2420** [comment]
related to https://github.com/openshiftio/openshift.io/issues/1392

**Comment by joshuawilson** [comment]
This only adds the doc, not a link to access it. 
@qodfathr Is that all that is required?

**Comment by qodfathr** [comment]
I don't need a link added to an existing page, no. But I do need the URL to work from an email. When you say "no link to access it," you don't mean that there isn't a valid URL to the file, do you? You just mean there isn't a link added to one of the web pages pointing to the file, right?

**Comment by joshuawilson** [comment]
Correct, there is nothing added to the web page to click on.

**Pull request merged**
