### PR TITLE
feat(shrinkwrap): add NPM shrinkwrap file for version locking

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**

### CODE REVIEW

**Comment by joshuawilson** [comment]
Why do you want Shrinkwrap here? This is just the landing page.
I have not heard why we should use Shrinkwrap over Package-lock.
Please reference the issue this PR addresses.

**Comment by samuzzal-choudhury** [comment]
@joshuawilson I saw three runtime dependencies for this application. Is there a reason for keeping those if this is the landing page for openshift.io.

As npm-shrinkwrap.json mandates the use of the specified locked versions for both direct and transitive dependencies, analytics team proposes its introduction in this repository. As you know, package manager may not honour the specified locked version for transitive dependencies in package-lock.json.

**Comment by joshuawilson** [comment]
Why do you think "transitive dependencies may not be honoured if package-lock.json is used"? That is what it is for.

While not an Angular app, it still imports JS libs and the package.json is useful for this.

**Comment by samuzzal-choudhury** [comment]
@joshuawilson Got the concern because of this issue https://github.com/npm/npm/issues/19458. Our objective is to scan the lock file that contains dependencies with locked versions that are actually used by the application. We are open to support package-lock.json in the application if that (the objective) is met. 

Please close this PR and the one that was opened for `fabric8-ui` for the same purpose and add package-lock.json for both of the repositories.

**Comment by maxandersen** [comment]
+1 on support package-lock.json since it with `npm ci` actually allow you to enforce failure if the two files are incompatible.

**Comment by samuzzal-choudhury** [comment]
@joshuawilson +1. As @miteshvp pointed out and I also agreed on earlier, we will have the support for package-lock.json shortly. Will you please introduce package-lock.json for this and `fabric8-ui` repos and let us know.

**Comment by joshuawilson** [comment]
Yes, I will take care of it.

**Pull request closed without merging**
