### PR TITLE
fix(rebranding): Introduce text only CodeReady Toolchain logo

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Introduce text only CodeReady Toolchain logo

Screenshots:
crtlogo

CodeReady Logo for less than 1400px
crtsmall

### CODE REVIEW

**Comment by christianvogt** [comment]
@nimishamukherjee @serenamarie125 Do we need to remove the favicon now?

**Comment by sunilmalagi** [comment]
@nimishamukherjee here is the clarification, in screenshot 1 bring the logo 5px down & screenshot 2 bring down the logo for only one px down, so that the logo is centre aligned (vertically).

Screenshot 1:
image

Screenshot 2:
image

**Comment by nimishamukherjee** [comment]
@sunilmalagi @serenamarie125 please check now based on 99fcd199af93f86cc06c715688390491347d89b0

crtlogo

crtsmalllogo

**Comment by sunilmalagi** [comment]
@nimishamukherjee look good to me...

**Pull request merged**
