### PR TITLE
fix(footer): Update date in footer

### PR DESCRIPTION
**Pull request by mindreeper2420**
Update footer from 2017 to 2018.

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Can't this be dynamic? Some way of using `new Date().getFullYear()` would do I guess?

**Comment by joshuawilson** [comment]
To me the question is, Why is this date there? If it always current year then what is the point? When would it be an old year?

**Comment by mindreeper2420** [comment]
That is a Brand/Marketing thing. Just updating to match redhat.com :-)

**Comment by joshuawilson** [comment]
@mindreeper2420 are you allowed to update the year whenever you want or do we need to wait for Brand?

**Comment by mindreeper2420** [comment]
@joshuawilson I just updated it to match the other properties. Any other changes to the footer (other than the product links) go through Brand (or an appropriate contact).

**Comment by bartoszmajsak** [comment]
Can we do it dynamic though? Otherwise, we will have to repeat this exercise every year... If we won't forget :)

**Comment by mindreeper2420** [comment]
Sure - it can be done with
`<script type="text/javascript">
  document.write(new Date().getFullYear());
</script>`

**Pull request merged**
