### PR TITLE
Update with New Design

### PR DESCRIPTION
**Pull request by mindreeper2420**
This PR updates the OpenShift.io landing page with a new design, new content and new flow.

**Included:**
* New Landing page
* New Features page
* New Get Involved page

**Flow:**
* Users will now be automatically redirected to https://openshift.io/_gettingstarted if they are already logged into the site and return to https://openshift.io. If a user has already gone through the Getting Started process, the site will automatically bring the user to https://openshift.io/_home.

**Features:**
* Utilizes CSS Grid
* Tested on all modern browsers, as well as IE11
* Accessibility requirements added to HTML pages, per standards
* Stylelint added to track `.less` files

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@joshuawilson this PR does not contain any tracking analytics updates. I have filed an issue (https://github.com/openshiftio/openshift.io/issues/767) for updating the various analytic pieces.

**Comment by mindreeper2420** [comment]
@catrobson @joshuawilson Burr and Brad will need to be notified when this new design is merged so that they can update their demo scripts.

**Comment by joshuawilson** [comment]
@catrobson who do we need to get approvals from on the way this looks and it's content?

**Comment by catrobson** [comment]
@joshuawilson unfortunately I don't think we have a way to stage this to get reviews.  We've generally gotten buy-in on this from stakeholders along the way.  I think the main thing we need to do is to get sign-off from Burr and Brad on making this update so they can update their workshops accordingly without disruption to customer experience.  I'll send an e-mail to coordinate.

**Comment by joshuawilson** [comment]
I read the email. I'll wait for feedback on that.

**Comment by joshuawilson** [comment]
fixes #737

**Pull request merged**
